name = "BB2"
uuid = "12aac903-9f7c-5d81-afc2-d9565ea332af"
authors = ["Elliot Saba <staticfloat@gmail.com>"]
version = "2.0.0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
BinaryBuilderGitUtils = "654d7472-7548-7361-4832-74694762694c"
BinaryBuilderPlatformExtensions = "213f2928-4d72-6f46-7461-4c705f634367"
BinaryBuilderProducts = "21737265-7a69-6e4f-4974-6375646f7270"
BinaryBuilderSources = "316c416d-4527-6863-7465-466137743047"
BinaryBuilderToolchains = "33566f4c-336c-3150-6d30-4374274e6143"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
JLLGenerator = "73536572-7074-4e69-5270-206c4c6a2061"
JLLPrefixes = "afc68a34-7891-4c5a-9da1-1c62935e7b0d"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MultiHashParsing = "73786568-6863-756d-6873-6168796e616d"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Sandbox = "9307e30f-c43e-9ca7-d17c-c2dc59df670d"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
TreeArchival = "216c6a2e-6c61-7669-6863-726165657274"
UserNSSandbox_jll = "b88861f7-1d72-59dd-91e7-a8cc876a4984"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
