name = "BinaryBuilderPlatformExtensions"
uuid = "213f2928-4d72-6f46-7461-4c705f634367"
authors = ["Elliot Saba <staticfloat@gmail.com>"]
version = "0.1.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[extras]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Artifacts", "Test"]
