name = "ScratchSpaceGarbageCollector"
uuid = "2b218182-314f-4389-a4eb-69d351d2272a"
authors = ["Elliot Saba <staticfloat@gmail.com>"]
version = "0.1.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
Dates = "1.9.0"
Scratch = "1.3.0"
TOML = "1.0.3"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
