name = "BinaryBuilderAuditor"
uuid = "53524979-5234-6e31-4220-6120654b694c"
authors = ["Elliot Saba <staticfloat@gmail.com>"]
version = "0.2.0"

[deps]
BinaryBuilderPlatformExtensions = "213f2928-4d72-6f46-7461-4c705f634367"
BinaryBuilderProducts = "21737265-7a69-6e4f-4974-6375646f7270"
BinaryBuilderSources = "316c416d-4527-6863-7465-466137743047"
BinaryBuilderToolchains = "33566f4c-336c-3150-6d30-4374274e6143"
JLLGenerator = "73536572-7074-4e69-5270-206c4c6a2061"
ObjectFile = "d8793406-e978-5875-9003-1fc021f44a92"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[compat]
BinaryBuilderProducts = "0.1"
BinaryBuilderToolchains = "0.1.1, 0.2"
JLLGenerator = "0.3"
ObjectFile = "0.4"
Pkg = "1.11.0"
julia = "1.6"

[extras]
BinaryBuilderToolchains = "33566f4c-336c-3150-6d30-4374274e6143"
JLLPrefixes = "afc68a34-7891-4c5a-9da1-1c62935e7b0d"
LazyJLLWrappers = "21706172-204c-4d4f-5420-656854206f44"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TreeArchival = "216c6a2e-6c61-7669-6863-726165657274"

[targets]
test = ["BinaryBuilderToolchains", "JLLPrefixes", "LazyJLLWrappers", "Test", "TreeArchival"]
