name = "KeywordArgumentExtraction"
uuid = "45533465-3150-2073-4772-41774b207255"
version = "1.0.1"
authors = ["Elliot Saba"]

[deps]
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[compat]
ExprTools = "0.1.10"
InteractiveUtils = "1.11.0"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
