name = "TreeArchival"
uuid = "216c6a2e-6c61-7669-6863-726165657274"
authors = ["Elliot Saba <staticfloat@gmail.com>"]
version = "0.1.0"

[deps]
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
Zstd_jll = "3161d3a3-bdf6-5164-811a-617609db77b4"
p7zip_jll = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
