authors = ["Elliot Saba <staticfloat@gmail.com>"]
name = "BinaryBuilderGitUtils"
uuid = "654d7472-7548-7361-4832-74694762694c"
version = "0.2.0"

[compat]
Git = "1.3.1"
Git_jll = ">= 2.36.1"
MultiHashParsing = "0.1"
julia = "1.9"

[deps]
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
Git_jll = "f8c6e375-362e-5223-8a59-34ff63f689eb"
MultiHashParsing = "73786568-6863-756d-6873-6168796e616d"
gh_cli_jll = "5d31d589-30fb-542f-b82d-10325e863e38"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
