name = "BinaryBuilderSources"
uuid = "316c416d-4527-6863-7465-466137743047"
authors = ["Elliot Saba <staticfloat@gmail.com>"]
version = "0.1.0"

[deps]
BinaryBuilderGitUtils = "654d7472-7548-7361-4832-74694762694c"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
JLLPrefixes = "afc68a34-7891-4c5a-9da1-1c62935e7b0d"
MultiHashParsing = "73786568-6863-756d-6873-6168796e616d"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
TreeArchival = "216c6a2e-6c61-7669-6863-726165657274"

[compat]
JLLPrefixes = "0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
